apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: <your_namespace_previously_created>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        # complete with the image and tag fields
        env:
        # complete with the PORT to expose the webapp
        ports:
        # complete to expose the ports in the container
      - name: redis
        # complete with the image and tag fields
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: yes
        # complete with the PORT to expose the redis
        ports:
        # complete to expose the ports in the container
