apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  # namespace: <your_namespace_previously_created>
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 3Gi
  hostPath:
    path: /data/redis/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  # namespace: <your_namespace_previously_created>
spec:
  # complete
  storageClassName: "" # you have to set this as an empty string
  