apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: <your_namespace_previously_created>
spec:
  selector:
    app: webapp
  ports:
  - name: http
    # complete
    port: # port to expose
    targetPort: # port in the container
  - name: redis
    # complete